### ISSUE TITLE
Error when triggering Sapphire Relic

### ISSUE THREAD

**Issue by dacja** [blakkthunderr/Blakkmod#2]
Exception in thread "LWJGL Application" com.badlogic.gdx.utils.GdxRuntimeException: java.lang.NoSuchMethodError: com.megacrit.cardcrawl.dungeons.AbstractDungeon.returnTrulyRandomCard(Lcom/megacrit/cardcrawl/cards/AbstractCard$CardType;Lcom/megacrit/cardcrawl/random/Random;)Lcom/megacrit/cardcrawl/cards/AbstractCard;
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication$1.run(LwjglApplication.java:133)
Caused by: java.lang.NoSuchMethodError: com.megacrit.cardcrawl.dungeons.AbstractDungeon.returnTrulyRandomCard(Lcom/megacrit/cardcrawl/cards/AbstractCard$CardType;Lcom/megacrit/cardcrawl/random/Random;)Lcom/megacrit/cardcrawl/cards/AbstractCard;
	at examplemod.relics.Sapphire.onUseCard(Sapphire.java:35)
	at com.megacrit.cardcrawl.actions.utility.UseCardAction.<init>(UseCardAction.java:40)
	at com.megacrit.cardcrawl.characters.AbstractPlayer.useCard(AbstractPlayer.java:1529)
	at com.megacrit.cardcrawl.actions.GameActionManager.getNextAction(GameActionManager.java:297)
	at com.megacrit.cardcrawl.actions.GameActionManager.update(GameActionManager.java:151)
	at com.megacrit.cardcrawl.rooms.AbstractRoom.update(AbstractRoom.java:267)
	at com.megacrit.cardcrawl.dungeons.AbstractDungeon.update(AbstractDungeon.java:2624)
	at com.megacrit.cardcrawl.core.CardCrawlGame.update(CardCrawlGame.java:892)
	at com.megacrit.cardcrawl.core.CardCrawlGame.render(CardCrawlGame.java:465)
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication.mainLoop(LwjglApplication.java:225)
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication$1.run(LwjglApplication.java:126)

**Comment by lascupa0788** [comment]
I had a very similar looking error with Emerald instead of Sapphire.

**Comment by RandomlyAwesome** [comment]
I had the same error upon triggering the Ruby as well.
